// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApiJs from "./api.js";

function fetchQuestion(prim) {
  return ApiJs.fetchQuestion(prim);
}

function fetchAnswers(prim) {
  return ApiJs.fetchAnswers(prim);
}

export {
  fetchQuestion,
  fetchAnswers,
}
/* ./api.js Not a pure module */
