// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as EndPage from "./EndPage.bs.js";
import * as HomePage from "./HomePage.bs.js";
import * as QuizPage from "./QuizPage.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useState(() => "Home");
  let setPage = match[1];
  let match$1 = React.useState(() => "");
  let setPlayerName = match$1[1];
  let match$2 = React.useState(() => 0);
  let setScore = match$2[1];
  switch (match[0]) {
    case "Home" :
      return JsxRuntime.jsx(HomePage.make, {
        onStart: name => {
          setPlayerName(param => name);
          setPage(param => "Quiz");
        }
      });
    case "Quiz" :
      return JsxRuntime.jsx(QuizPage.make, {
        onComplete: finalScore => {
          setScore(param => finalScore);
          setPage(param => "End");
        }
      });
    case "End" :
      return JsxRuntime.jsx(EndPage.make, {
        playerName: match$1[0],
        score: match$2[0],
        onReplay: () => {
          setScore(param => 0);
          setPage(param => "Home");
        }
      });
  }
}

let make = App;

export {
  make,
}
/* react Not a pure module */
