// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function EndPage(props) {
  let onReplay = props.onReplay;
  let score = props.score;
  let message = score === 4 ? "Score parfait !" : (
      score >= 3 ? "Excellent résultat !" : (
          score >= 2 ? "Bon travail !" : "Continuez à vous entraîner !"
        )
    );
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Bravo !"
      }),
      JsxRuntime.jsx("h2", {
        children: props.playerName
      }),
      JsxRuntime.jsx("div", {
        children: String(score) + " / 4",
        className: "final-score"
      }),
      JsxRuntime.jsx("div", {
        children: message,
        className: "score-label"
      }),
      JsxRuntime.jsx("button", {
        children: "Rejouer",
        className: "btn btn-primary",
        onClick: param => onReplay()
      })
    ],
    className: "page end-page"
  });
}

let make = EndPage;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
