// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

function HomePage(props) {
  let onStart = props.onStart;
  let match = React.useState(() => "");
  let setName = match[1];
  let name = match[0];
  let handleSubmit = e => {
    e.preventDefault();
    if (name.length > 0) {
      return onStart(name);
    }
  };
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "QCM"
      }),
      JsxRuntime.jsx("h2", {
        children: "Bienvenue au Quiz !"
      }),
      JsxRuntime.jsxs("form", {
        children: [
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("label", {
                children: "Votre nom :",
                htmlFor: "player-name"
              }),
              JsxRuntime.jsx("input", {
                className: "name-input",
                id: "player-name",
                placeholder: "Entrez votre nom",
                type: "text",
                value: name,
                onChange: e => setName(param => e.target.value)
              })
            ],
            className: "input-group"
          }),
          JsxRuntime.jsx("button", {
            children: "Commencer",
            className: "btn btn-primary",
            disabled: name.length === 0,
            type: "submit"
          })
        ],
        onSubmit: handleSubmit
      })
    ],
    className: "page home-page"
  });
}

let make = HomePage;

export {
  make,
}
/* react Not a pure module */
