// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

let container = document.querySelector("#root");

if (!(container == null)) {
  let root = Client.createRoot(container);
  root.render(JsxRuntime.jsx(App.make, {}));
}

/* container Not a pure module */
