// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Api from "./Api.bs.js";
import * as React from "react";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

let shuffle = (function shuffle(arr) {
    const copy = arr.slice();
    for (let i = copy.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      const tmp = copy[i];
      copy[i] = copy[j];
      copy[j] = tmp;
    }
    return copy;
  });

function QuizPage(props) {
  let onComplete = props.onComplete;
  let match = React.useState(() => "Loading");
  let setState = match[1];
  let state = match[0];
  React.useEffect(() => {
    let loadOne = async id => {
      let title = await Api.fetchQuestion(id);
      let answers = await Api.fetchAnswers(id);
      return {
        id: id,
        title: title,
        answers: shuffle(answers)
      };
    };
    let loadAll = async () => {
      try {
        let q1 = await loadOne(1);
        let q2 = await loadOne(2);
        let q3 = await loadOne(3);
        let q4 = await loadOne(4);
        let questions = shuffle([
          q1,
          q2,
          q3,
          q4
        ]);
        return setState(param => ({
          TAG: "Playing",
          questions: questions,
          currentIndex: 0,
          score: 0,
          selectedIndex: undefined
        }));
      } catch (exn) {
        return setState(param => ({
          TAG: "LoadError",
          _0: "Erreur lors du chargement des questions."
        }));
      }
    };
    loadAll();
  }, []);
  if (typeof state !== "object") {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsx("div", {
        children: "Chargement des questions...",
        className: "loading"
      }),
      className: "page"
    });
  }
  if (state.TAG !== "Playing") {
    return JsxRuntime.jsx("div", {
      children: JsxRuntime.jsx("div", {
        children: state._0,
        className: "error"
      }),
      className: "page"
    });
  }
  let selectedIndex = state.selectedIndex;
  let currentIndex = state.currentIndex;
  let questions = state.questions;
  let total = questions.length;
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: "Score : " + String(state.score),
        className: "score-badge"
      }),
      JsxRuntime.jsx("div", {
        children: "Question " + String(currentIndex + 1 | 0) + " / " + String(total),
        className: "question-number"
      }),
      JsxRuntime.jsx("h2", {
        children: questions[currentIndex].title,
        className: "question-title"
      }),
      JsxRuntime.jsx("div", {
        children: Belt_Array.mapWithIndex(questions[currentIndex].answers, (i, answer) => {
          let buttonClass = selectedIndex !== undefined ? (
              answer.correct ? "btn answer-btn correct" : (
                  i === selectedIndex ? "btn answer-btn incorrect" : "btn answer-btn"
                )
            ) : "btn answer-btn";
          return JsxRuntime.jsx("button", {
            children: answer.title,
            className: buttonClass,
            disabled: Belt_Option.isSome(selectedIndex),
            onClick: param => {
              let isCorrect = answer.correct;
              if (typeof state !== "object") {
                return;
              }
              if (state.TAG !== "Playing") {
                return;
              }
              if (state.selectedIndex !== undefined) {
                return;
              }
              let score = state.score;
              let currentIndex = state.currentIndex;
              let questions = state.questions;
              let newScore = isCorrect ? score + 1 | 0 : score;
              setState(param => ({
                TAG: "Playing",
                questions: questions,
                currentIndex: currentIndex,
                score: newScore,
                selectedIndex: i
              }));
              setTimeout(() => {
                let nextIndex = currentIndex + 1 | 0;
                if (nextIndex >= questions.length) {
                  return onComplete(newScore);
                } else {
                  return setState(param => ({
                    TAG: "Playing",
                    questions: questions,
                    currentIndex: nextIndex,
                    score: newScore,
                    selectedIndex: undefined
                  }));
                }
              }, 1000);
            }
          }, String(i));
        }),
        className: "answers-grid"
      })
    ],
    className: "page quiz-page"
  });
}

let make = QuizPage;

export {
  shuffle,
  make,
}
/* Api Not a pure module */
